export enum MembershipStatus {
  INVITED = 'INVITED',
  VISITOR = 'VISITOR',
  PROSPECT = 'PROSPECT',
  MEMBER = 'MEMBER',
  CHILD = 'CHILD',
  DISCIPLINED = 'DISCIPLINED',
  EXCOMMUNICATED = 'EXCOMMUNICATED',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}
