export enum MissionSourceType {
  CHURCH_NEED_SIGNAL = 'CHURCH_NEED_SIGNAL',
  UNREACHED_AREA = 'UNREACHED_AREA',
  MANUAL = 'MANUAL',
}

export enum MissionOutcomeType {
  CHURCH_PLANTED = 'CHURCH_PLANTED',
  SMALL_GROUP_ESTABLISHED = 'SMALL_GROUP_ESTABLISHED',
  PARTNER_CHURCH_FOUND = 'PARTNER_CHURCH_FOUND',
  CANCELLED = 'CANCELLED',
  MERGED = 'MERGED',
  OTHER = 'OTHER',
}

export enum MissionNeedStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MissionCollaborationStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum MissionProjectStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MissionNeedType {
  PRAYER = 'PRAYER',
  FINANCIAL = 'FINANCIAL',
  VOLUNTEER = 'VOLUNTEER',
  MATERIAL = 'MATERIAL',
  LOGISTIC = 'LOGISTIC',
}

export enum MissionReportCategory {
  PROGRESS = 'PROGRESS',
  TESTIMONY = 'TESTIMONY',
  PRAYER_REQUEST = 'PRAYER_REQUEST',
  EVENT = 'EVENT',
  BAPTISM = 'BAPTISM',
  SMALL_GROUP = 'SMALL_GROUP',
  CHURCH_PLANTING = 'CHURCH_PLANTING',
  CHALLENGE = 'CHALLENGE',
  OTHER = 'OTHER',
}
