export enum ChurchClaimStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum PublicChurchRelationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

/**
 * Public network relation types.
 * These are NOT ERP memberships (ChurchPerson).
 *
 * COMMUNITY_MEMBER was previously named MEMBER.
 * Renamed to avoid confusion with ERP membership.
 */
export enum PublicChurchRelationType {
  COMMUNITY_MEMBER = 'COMMUNITY_MEMBER',
  REGULAR_VISITOR = 'REGULAR_VISITOR',
}

export enum EcosystemHistoryEvent {
  CLAIM_SUBMITTED = 'CLAIM_SUBMITTED',
  CLAIM_APPROVED = 'CLAIM_APPROVED',
  VISITOR_JOINED = 'VISITOR_JOINED',
  VISITOR_LEFT = 'VISITOR_LEFT',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  VISITOR_TO_MEMBER = 'VISITOR_TO_MEMBER',
  MEMBER_TO_VISITOR = 'MEMBER_TO_VISITOR',
  ADMIN_ASSIGNED = 'ADMIN_ASSIGNED',
  ADMIN_REMOVED = 'ADMIN_REMOVED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  COMMUNITY_JOIN_REJECTED = 'COMMUNITY_JOIN_REJECTED',
  ECCLESIAL_ROLE_CHANGED = 'ECCLESIAL_ROLE_CHANGED',
}

export enum NeedSignalStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}

export enum NeedSignalCloseReason {
  TEMPORARY = 'TEMPORARY',
  RESOLVED = 'RESOLVED',
}

export enum NeedSignalType {
  CHURCH_PLANT_NEEDED = 'CHURCH_PLANT_NEEDED',
}

export enum EcclesialRole {
  NONE = 'NONE',
  PASTOR = 'PASTOR',
  ELDER = 'ELDER',
  BISHOP = 'BISHOP',
  DEACON = 'DEACON',
  MINISTRY_LEADER = 'MINISTRY_LEADER',
}

export enum ChurchDenomination {
  INDEPENDENT = 'INDEPENDENT',
  BAPTIST = 'BAPTIST',
  PRESBYTERIAN = 'PRESBYTERIAN',
  REFORMED = 'REFORMED',
  METHODIST = 'METHODIST',
  ANGLICAN = 'ANGLICAN',
  LUTHERAN = 'LUTHERAN',
  PENTECOSTAL = 'PENTECOSTAL',
  CHRISTIAN_CHURCH = 'CHRISTIAN_CHURCH',
  OTHER = 'OTHER',
}

export enum DayOfWeek {
  SUNDAY = 'SUNDAY',
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
}

export enum ChurchGovernment {
  CONGREGATIONAL = 'CONGREGATIONAL',
  ELDER_LED = 'ELDER_LED',
  PRESBYTERIAN = 'PRESBYTERIAN',
  EPISCOPAL = 'EPISCOPAL',
  OTHER = 'OTHER',
}

export enum BaptismStance {
  CREDOBAPTIST = 'CREDOBAPTIST',
  PAEDOBAPTIST = 'PAEDOBAPTIST',
  MIXED = 'MIXED',
  OTHER = 'OTHER',
}

export enum SpiritualGiftsStance {
  CONTINUATIONIST = 'CONTINUATIONIST',
  CESSATIONIST = 'CESSATIONIST',
  CAUTIOUS_CONTINUATIONIST = 'CAUTIOUS_CONTINUATIONIST',
}

export enum EschatologyStance {
  PREMILLENNIAL = 'PREMILLENNIAL',
  AMILLENNIAL = 'AMILLENNIAL',
  POSTMILLENNIAL = 'POSTMILLENNIAL',
  OTHER = 'OTHER',
}

export enum GenderRolesStance {
  COMPLEMENTARIAN = 'COMPLEMENTARIAN',
  EGALITARIAN = 'EGALITARIAN',
}

export enum LordsSupperStance {
  MEMORIAL = 'MEMORIAL',
  SPIRITUAL_PRESENCE = 'SPIRITUAL_PRESENCE',
  REAL_PRESENCE = 'REAL_PRESENCE',
  OTHER = 'OTHER',
}
