export enum NeedEngagementStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
}

export enum NeedEngagementType {
  CONTACT = 'CONTACT',
  PRAYER = 'PRAYER',
  DISCIPLESHIP = 'DISCIPLESHIP',
  VISIT = 'VISIT',
  EVANGELISM = 'EVANGELISM',
  FINANCIAL_SUPPORT = 'FINANCIAL_SUPPORT',
  MISSION_PROJECT = 'MISSION_PROJECT',
  RESOLVED = 'RESOLVED',
}

export enum NeedEntityType {
  PERSONAL_NEED = 'PERSONAL_NEED',
  CHURCH_NEED = 'CHURCH_NEED',
  UNREACHED_AREA = 'UNREACHED_AREA',
}

export enum NeedInformationCategory {
  GENERAL = 'GENERAL',
  LANGUAGE = 'LANGUAGE',
  CULTURE = 'CULTURE',
  RELIGION = 'RELIGION',
  DEMOGRAPHICS = 'DEMOGRAPHICS',
  SECURITY = 'SECURITY',
  TRANSPORT = 'TRANSPORT',
  CONTACT = 'CONTACT',
  LEGAL = 'LEGAL',
  RESOURCES = 'RESOURCES',
  TESTIMONY = 'TESTIMONY',
  OTHER = 'OTHER',
}

export enum NeedInformationEntityType {
  NEED_SIGNAL = 'NEED_SIGNAL',
  CHURCH_NEED_SIGNAL = 'CHURCH_NEED_SIGNAL',
  UNREACHED_AREA = 'UNREACHED_AREA',
}

export enum NeedInformationSourceType {
  PERSONAL_OBSERVATION = 'PERSONAL_OBSERVATION',
  LOCAL_CONTACT = 'LOCAL_CONTACT',
  MISSIONARY_REPORT = 'MISSIONARY_REPORT',
  CHURCH_REPORT = 'CHURCH_REPORT',
  EXTERNAL_SOURCE = 'EXTERNAL_SOURCE',
}

export enum UnreachedAreaStatus {
  OPEN = 'OPEN',
  REACHED = 'REACHED',
}

export enum NeedSignalAction {
  EDIT = 'EDIT',
  CLOSE = 'CLOSE',
  REOPEN = 'REOPEN',
}

export enum ChurchNeedSignalAction {
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  CLOSE = 'CLOSE',
  REOPEN = 'REOPEN',
  SUPPORT = 'SUPPORT',
  ADD_INFO = 'ADD_INFO',
}
